import { raw } from "hono/html";
import {
  ArrowDown,
  ArrowUp,
  Ban,
  Building2,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleStop,
  Clapperboard,
  Clock,
  ClockFading,
  Copy,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Film,
  Funnel,
  Gauge,
  HardDrive,
  Image,
  Hourglass,
  Info,
  KeyRound,
  Layers,
  LayoutGrid,
  LifeBuoy,
  Link,
  List,
  ListChecks,
  ListRestart,
  ListVideo,
  LoaderCircle,
  LogIn,
  LogOut,
  Menu,
  Merge,
  MonitorSmartphone,
  PanelLeft,
  Pencil,
  Play,
  PlugZap,
  Plus,
  RadioTower,
  RefreshCw,
  RotateCcw,
  Rss,
  Save,
  ScrollText,
  Search,
  Server,
  Settings,
  Split,
  SlidersHorizontal,
  Sparkles,
  Star,
  Trash,
  TriangleAlert,
  Tv,
  Unlink,
  WandSparkles,
  Workflow,
  X,
} from "lucide-static";

/**
 * Lucide icons, inlined as SVG at render time: no icon font, no script. Named imports only, so
 * esbuild keeps just these. Add an icon here before using it: a page never imports lucide itself.
 */
const ICONS = {
  alert: CircleAlert,
  "arrow-down": ArrowDown,
  "arrow-up": ArrowUp,
  auto: WandSparkles,
  caches: HardDrive,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  clients: MonitorSmartphone,
  clock: Clock,
  copy: Copy,
  dashboard: Gauge,
  database: Database,
  devices: Tv,
  download: Download,
  edit: Pencil,
  epg: CalendarClock,
  error: TriangleAlert,
  external: ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  fallback: LifeBuoy,
  favorites: Star,
  file: FileText,
  film: Film,
  grid: LayoutGrid,
  group: Layers,
  history: ClockFading,
  image: Image,
  info: Info,
  key: KeyRound,
  link: Link,
  list: List,
  live: RadioTower,
  loader: LoaderCircle,
  login: LogIn,
  logout: LogOut,
  logs: ScrollText,
  menu: Menu,
  merge: Merge,
  more: Ellipsis,
  none: Ban,
  panel: PanelLeft,
  pipeline: Workflow,
  play: Play,
  plus: Plus,
  programmes: ListVideo,
  refresh: RefreshCw,
  reset: ListRestart,
  retry: RotateCcw,
  rules: Funnel,
  save: Save,
  search: Search,
  series: Clapperboard,
  server: Server,
  settings: Settings,
  source: Rss,
  sparkles: Sparkles,
  split: Split,
  steps: ListChecks,
  stop: CircleStop,
  studios: Building2,
  success: CircleCheck,
  test: PlugZap,
  trash: Trash,
  tune: SlidersHorizontal,
  unlink: Unlink,
  waitlist: Hourglass,
  x: X,
} as const;

export type IconName = keyof typeof ICONS;

/** `cls` replaces Lucide's own classes: a `size-*` there overrides the 16 px Basecoat gives an icon in a button or a menu. */
export const Icon = ({ name, cls = "" }: { name: IconName; cls?: string }) =>
  raw(
    ICONS[name]
      .replace(/class="[^"]*"/, `class="${cls}" aria-hidden="true"`)
      .replace(/\s*\n\s*/g, " ")
      .trim(),
  );
